### ISSUE TITLE
Latest build gives error on uvicorn launch

### ISSUE THREAD

**Issue by lzardy** [radames/Real-Time-Latent-Consistency-Model#2]
Installing on Windows 10 using env produces this error:

```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\venv\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\venv\lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\app-img2img.py", line 81, in <module>
    pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\venv\lib\site-packages\torch\__init__.py", line 1723, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 583, in optimize
    check_if_dynamo_supported()
  File "M:\Accessories\Real-Time-Latent-Consistency-Model\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 535, in check_if_dynamo_supported
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile
```

Python version: 3.10.6
x64 bit architecture
RTX 3060, Intel CPU

**Comment by radames** [comment]
hi @lzardy you can comment these lines

https://github.com/radames/Real-Time-Latent-Consistency-Model/blob/main/app-img2img.py#L80-L82
and 
https://github.com/radames/Real-Time-Latent-Consistency-Model/blob/main/app-txt2img.py#L80-L82
