### ISSUE TITLE
"ReferenceError: Blob is not defined" during setting up frontend

### ISSUE THREAD

**Issue by vincentlux** [radames/Real-Time-Latent-Consistency-Model#27]
Thanks for this wonderful work! I tried to run the demo (in a wsl2 environment) however ran into this problem when trying to setup the frontend:

```
npm install && npm run build && cd ..

up to date, audited 266 packages in 3s

59 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> frontend@0.0.1 build
> vite build


vite v4.5.0 building SSR bundle for production...
✓ 94 modules transformed.

vite v4.5.0 building for production...
✓ 87 modules transformed.
.svelte-kit/output/client/_app/version.json                              0.03 kB │ gzip:  0.05 kB
.svelte-kit/output/client/.vite/manifest.json                            2.77 kB │ gzip:  0.48 kB
.svelte-kit/output/client/_app/immutable/assets/2.4b49e46c.css           0.88 kB │ gzip:  0.27 kB
.svelte-kit/output/client/_app/immutable/assets/0.82666576.css           9.71 kB │ gzip:  2.75 kB
.svelte-kit/output/client/_app/immutable/nodes/0.5ed3b7c1.js             0.60 kB │ gzip:  0.38 kB
.svelte-kit/output/client/_app/immutable/chunks/index.57cd3851.js        0.92 kB │ gzip:  0.57 kB
.svelte-kit/output/client/_app/immutable/nodes/1.0b2d00ed.js             1.03 kB │ gzip:  0.59 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.49bed12e.js   2.45 kB │ gzip:  1.26 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.d303939e.js    2.49 kB │ gzip:  1.16 kB
.svelte-kit/output/client/_app/immutable/entry/app.2f014e65.js           5.94 kB │ gzip:  2.34 kB
.svelte-kit/output/client/_app/immutable/chunks/index.b58b6c9b.js        6.16 kB │ gzip:  2.60 kB
.svelte-kit/output/client/_app/immutable/entry/start.35296672.js        24.87 kB │ gzip:  9.81 kB
.svelte-kit/output/client/_app/immutable/nodes/2.45ba902c.js            72.26 kB │ gzip: 21.33 kB
✓ built in 2.90s
ReferenceError: Blob is not defined
    at file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/.svelte-kit/output/server/entries/pages/_page.svelte.js:22:49
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async Module.component (file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/.svelte-kit/output/server/nodes/2.js:5:59)
    at async Promise.all (index 1)
    at async render_response (file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/.svelte-kit/output/server/index.js:1322:21)
    at async render_page (file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/.svelte-kit/output/server/index.js:2162:12)
    at async resolve (file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/.svelte-kit/output/server/index.js:2743:24)
    at async respond (file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/.svelte-kit/output/server/index.js:2629:22)

node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/node_modules/@sveltejs/kit/src/core/config/options.js:212:13
    at file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
    at save (file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///mnt/c/Users/vince/Documents/foco/code/Real-Time-Latent-Consistency-Model/frontend/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:298:10)
    at Worker.[kOnMessage] (node:internal/worker:309:37)
    at MessagePort.<anonymous> (node:internal/worker:205:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

May I ask if you have any clue what the problem is? Thanks for your help in advance!

**Comment by radames** [comment]
hi @vincentlux , that's odd, what's your node version?

**Comment by vincentlux** [comment]
hi @radames , yeah that's the problem, after upgrading to node 19 everything is good. Thanks!
