### ISSUE TITLE
webgui can't start

### ISSUE THREAD

**Issue by banditsmile** [radames/Real-Time-Latent-Consistency-Model#32]
python run.py --reload --pipeline controlnetLoraSD15

<img width="1700" alt="image" src="https://github.com/radames/Real-Time-Latent-Consistency-Model/assets/2239356/79ea30de-7757-40ce-8dad-1857be5a6b8a">

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enumerateDevices')
    at Object.enumerateDevices (2.7386ed29.js:1:39137)
    at HTMLButtonElement.B (2.7386ed29.js:8:2589)
    at scheduler.d303939e.js:1:1497
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.N (scheduler.d303939e.js:1:1484)
    at HTMLButtonElement.l (2.7386ed29.js:1:3003)
```

**Comment by radames** [comment]
probably related to browser security

https://github.com/radames/Real-Time-Latent-Consistency-Model/issues/17

**Comment by banditsmile** [comment]
thank you
