### ISSUE TITLE
pix2pixTurbo: "AttributeError: 'AutoencoderKL' object has no attribute 'add_adapter'"

### ISSUE THREAD

**Issue by jfranecki** [radames/Real-Time-Latent-Consistency-Model#38]
Unable to run `python server/main.py --reload --pipeline pix2pixTurbo`

```
(venv) justin@DynamicEVO:~/AI/Real-Time-Latent-Consistency-Model$ python server/main.py --reload --pipeline pix2pixTurbo


host: 0.0.0.0
port: 7860
reload: True
max_queue_size: 0
timeout: 0.0
safety_checker: False
torch_compile: False
taesd: True
pipeline: pix2pixTurbo
ssl_certfile: None
ssl_keyfile: None
sfast: False
onediff: False
compel: False
debug: False


Device: cuda
torch_dtype: torch.float16
/home/justin/AI/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/justin/AI/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/justin/AI/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/justin/AI/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/home/justin/AI/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/justin/AI/Real-Time-Latent-Consistency-Model/server/main.py", line 166, in <module>
    pipeline = pipeline_class(config, device, torch_dtype)
  File "/home/justin/AI/Real-Time-Latent-Consistency-Model/server/pipelines/pix2pixTurbo.py", line 98, in __init__
    self.model = Pix2Pix_Turbo("edge_to_image")
  File "/home/justin/AI/Real-Time-Latent-Consistency-Model/server/pipelines/pix2pix/pix2pix_turbo.py", line 134, in __init__
    vae.add_adapter(vae_lora_config, adapter_name="vae_skip")
  File "/home/justin/AI/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in __getattr__
    return super().__getattr__(name)
  File "/home/justin/AI/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AutoencoderKL' object has no attribute 'add_adapter'
```

**Comment by radames** [comment]
hi @jfranecki , can you please check which diffusers version are you on? that specific pipeline requires `diffusers==0.25.1`
