### ISSUE TITLE
AttributeError: module diffusers has no attribute LCMScheduler

### ISSUE THREAD

**Issue by boricuapab** [radames/Real-Time-Latent-Consistency-Model#4]
```
Traceback (most recent call last):s: 100%|████████████████████████████████████████| 3.44G/3.44G [02:13<00:00, 32.7MB/s]
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\LCMRT\Real-Time-Latent-Consistency-Model\app-img2img.py", line 62, in <module>
    pipe = DiffusionPipeline.from_pretrained(
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1105, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 391, in load_sub_model
    class_obj, class_candidates = get_class_obj_and_candidates(
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 319, in get_class_obj_and_candidates
    class_obj = getattr(library, class_name)
  File "C:\ProgramData\miniconda3\envs\LCMRT\lib\site-packages\diffusers\utils\import_utils.py", line 677, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module diffusers has no attribute LCMScheduler

**Comment by radames** [comment]
hi @boricuapab, please update your diffusers! I'm now using LCM direct from the newest version
`pip install -U diffusers==0.22.1`

**Comment by boricuapab** [comment]
Thanks for the quick response, and for your fantastic work.

After updating diffusers it's working again.
