### ISSUE TITLE
Diffusers requirements needed an bump.

### ISSUE THREAD

**Issue by JPW0080** [radames/Real-Time-Latent-Consistency-Model#40]
On my side, diffusers threw an error:

(venv) (base) ws2testing@DESKTOP-EU7ASQA:~/ws2testing/Real-Time-Latent-Consistency-Model$ python server/main.py --reload --pipeline controlnetHyperSD

host: 0.0.0.0
port: 7860
reload: True
max_queue_size: 0
timeout: 0.0
safety_checker: False
torch_compile: False
taesd: True
pipeline: controlnetHyperSD
ssl_certfile: None
ssl_keyfile: None
sfast: False
onediff: False
compel: False
debug: False

Device: cuda
torch_dtype: torch.float16
/home/wsl2testing/wsl2testing/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/wsl2testing/wsl2testing/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/wsl2testing/wsl2testing/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/wsl2testing/wsl2testing/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/wsl2testing/wsl2testing/Real-Time-Latent-Consistency-Model/server/main.py", line 165, in <module>
    pipeline_class = get_pipeline_class(config.pipeline)
  File "/home/wsl2testing/wsl2testing/Real-Time-Latent-Consistency-Model/server/util.py", line 9, in get_pipeline_class
    module = import_module(f"pipelines.{pipeline_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wsl2testing/wsl2testing/Real-Time-Latent-Consistency-Model/server/pipelines/controlnetHyperSD.py", line 1, in <module>
    from diffusers import (
ImportError: cannot import name 'TCDScheduler' from 'diffusers' (/home/wsl2testing/wsl2testing/Real-Time-Latent-Consistency-Model/venv/lib/python3.10/site-packages/diffusers/__init__.py)

**Comment by AtomicNixon** [comment]
pip install --upgrade diffusers
...worked for me.  Now running diffusers==0.27.2
